### ISSUE TITLE
nodejs-legacy needed

### ISSUE THREAD

**Issue by Alex-Ph** [Devoxx4KidsDE/workshop-maze-vr#8]
Hi,
I used your readme to install the workshop on ubuntu 14.04. After "npm install" I had to install nodejs-legacy (sudo apt-get install nodejs-legacy) as well, before I was able to "npm start" the server. 

Otherwise I got an npm start error "this failure might be due to the use of legacy binary"

**Comment by derTobsch** [comment]
Hey, thanks for your issue. We will take a look.

**Comment by honnel** [comment]
Which node version was producing the error during `npm start`?
For our workshops we are currently using Node v6.0.0. Have you tried `nvm` (Node Version Manager , https://github.com/creationix/nvm)? Its an convenient way to select any node version depending on the project.

**Comment by derTobsch** [comment]
@Alex-Ph do you still have problems with the npm version? otherwise we would close this issue.
